### ISSUE TITLE
Mame Advance ,always show "copyright" warning

### ISSUE THREAD

**Issue by cole123** [shantigilbert/LibreELEC.tv#18]
Hi ,Niabi, Nice work for the retro game on MXQ .
when I install Sx05 Retro Edition V1.4 and play mame advance ,it always show  "copyright" warning and the gamepad is out of control ,is there any config file where I can hide the warning. or some way else can solve this .besides,what is the version of the name can be used for this emulator .thanks

**Comment by shantigilbert** [comment]
I will look into hiding the warning, but you can also just move the gamepad/joystick around and it will remove itself. what controller are you using?

**Comment by shantigilbert** [comment]
edit /storage/.advance/advmame.rc  and change 
misc_quiet no
to 
misc_quiet yes

I will add this as default for the 1.5 release.
