### ISSUE TITLE
Attract Mode does not compile

### ISSUE THREAD

**Issue by shantigilbert** [shantigilbert/LibreELEC.tv#36]
Even tho Sx05RE is focused on Emulationstation it would be great to also have the option for other front-ends, Pegasus works very well in Sx05RE but it is still very young to be the main front-end.

I have been trying to compile Attract Mode for a while now, and I have made some advances compiling SFML which is needed by Attract Mode, but I can't seem to get the actual FE to compile.

**Comment by shantigilbert** [comment]
This is the error I get: 
`<built-in>: note: this is the location of the previous definition
In file included from /home/sg/sx05re/Kszaq/build.Sx05RE-S905.arm-1.6/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/libavutil/samplefmt.h:24:0,
                 from /home/sg/sx05re/Kszaq/build.Sx05RE-S905.arm-1.6/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/libavcodec/avcodec.h:31,
                 from src/media.cpp:30:
/home/sg/sx05re/Kszaq/build.Sx05RE-S905.arm-1.6/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/libavutil/avutil.h: In function 'void* av_x_if_null(const void*, const void*)':
/home/sg/sx05re/Kszaq/build.Sx05RE-S905.arm-1.6/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/libavutil/avutil.h:302:40: error: cast from 'const void*' to 'intptr_t {aka int}' loses precision [-fpermissive]
     return (void *)(intptr_t)(p ? p : x);
`

**Comment by shantigilbert** [comment]
@asakous sorry for the late reply.

I read all of the post when I was trying to compile SFML and it worked for most of it, but I still get the same problem with Attract Mode.

**Comment by shantigilbert** [comment]
@asakous are this the errors you get ?

undefined reference to glBlendEquationSeparateOES

?

**Comment by asakous** [comment]
@shantigilbert  I am not sure exactly function name . but very similar to  undefined reference to glBlendEquationXXXX. You run into the same problem.^^

**Comment by shantigilbert** [comment]
yeah, I get 2 similar errors at linking, and can't move forward from there :(

**Comment by asakous** [comment]
according to ODROD fourm
glBlendEquationSeparateOES and glBlendFuncSeparateOES available on Mali T628 r9p0 drivers
So Attract-Mode on  mail400 and 450 GPU platform probably not gonna happen  

2016-01-15:
libsfml-odroid
SFML - Simple and Fast Multimedia Library (OpenGLES build) version 2.3.2
in jessie/main package list
-> requirement for attract
attract
Attract-Mode emulator frontend
in jessie/main package list
-> requested by @tipoto
I only did some initial testing, for me it seems fullscreen is not 100% working correctly, it also required glBlendEquationSeparateOES and glBlendFuncSeparateOES during linking which only seems to be available for XU3/XU4.
updated libgl-odroid package
-> in sync with ptitSeb's branch of glshim

2016-01-14:
updated XU3/XU4 Kernel and Headers to be in sync with HardKernel (recent changes for Mali T628 r9p0 drivers, and additional bugfixes)
updated malit628-odroid package with current r9p0 drivers

**Comment by shantigilbert** [comment]
Well there we go then, attract will never happen unless someone with more knowledge than myself can create a working patch. :( 

thanks for the help @asakous, I will no close this issue
