### ISSUE TITLE
How can I change the resolution for ES and Retroarch?

### ISSUE THREAD

**Issue by SumavisionQ5** [shantigilbert/LibreELEC.tv#42]
First, I am really apreciated for your great efforts on this project. My friends and I all like your fantastic build very much. 
Due the limitation of some old monitors, many people have to use 720p or lower resolution. However, sx05re can only output 1080p, or the screen would not be correctly showed. I can not find any docs anywhere, and I can't regist an account on forum of LIBREELEC, so I have to ask this question here.
And, by the way, someone posted the CVBS output patch codes for S905, can you apply it to your build?
https://forum.libreelec.tv/thread/8869-nexbox-a95x-s905x-soc-analog-output-not-working/

**Comment by shantigilbert** [comment]
I have never tried using a lower resolution, but you can change it here.

Change
hdmimode=1080p60hz
To
hdmimode=720p60hz


https://github.com/shantigilbert/LibreELEC.tv/blob/Sx05RE/projects/S905/initramfs/platform_init

But you need to compile your own build. 

That patch will soon be on the Kszaq build, and when that happens I will merge it here. Sorry but I have no way to test if anything will be broken as the only box I have does not have CVBS out :( 

However if you decide to build your own version you can easily apply it, just download the patch and put it in /projects/S905/patches/kodi/ 

Hope that helps!

**Comment by SumavisionQ5** [comment]
Can CVBS output patch work for ES and Lakka? As you said, this is an emulation build, so I don't care about KODI stuff.  
Do I have to compile my build if I want CVBS output or 720p? Any way to edit a configuration file to make changes working?
Sorry to ask so many questions, as I don't know much about Linux.

**Comment by shantigilbert** [comment]
As I mentioned before, since I don't have a box that outputs CVBS I have no way of knowing, in theory it should work.

**Comment by SumavisionQ5** [comment]
Thank you. If you need someone to test it, I am pleased to help.

**Comment by shantigilbert** [comment]
What happens if you just connect it as it, do you get no signal ?

**Comment by SumavisionQ5** [comment]
Yes, I get no signal.

**Comment by shantigilbert** [comment]
There is a new version of Libreelec that supposedly supports CVBS, I will compile a version for you to test tonight.

**Comment by SumavisionQ5** [comment]
Thank you very much!

**Comment by shantigilbert** [comment]
Or you can actually test this by installing the latest Kszaq build from here
https://forum.libreelec.tv/thread/2156-8-0-2c-libreelec-8-0-for-s905-s905x

Check if you get signal at boot (before Kodi starts).

please make sure no HDMI is connected to your device.

**Comment by SumavisionQ5** [comment]
I can test Kszaq's build tonight, but I'm really eager to know whether CVBS output is working properly for ES and Retroarch.

**Comment by shantigilbert** [comment]
Please try v1.6 I just uploaded

**Comment by SumavisionQ5** [comment]
Thank you, buddy. You are the best!

**Comment by shantigilbert** [comment]
Did it work?

**Comment by SumavisionQ5** [comment]
No, it does not work properly. It ouputs signals, but only a small part showed. 
![tim 20170622123343](https://user-images.githubusercontent.com/29566203/27417416-d4135d70-5746-11e7-8f97-a900b92f6ced.jpg)

**Comment by shantigilbert** [comment]
Well its a step in the right direction, it looks like its scaling to 720 or 1080 and your TV is only capable of 480.

Connect an ethernet cable so you cas SSH to your box so we can test some stuff

First post the result of this:

`cat /sys/class/display/mode`

and then try to type this:

```
fbset -fb /dev/fb0 -g 720 480 1920 2160 32
fbset -fb /dev/fb1 -g 32 32 32 32 32
echo 0 > /sys/class/graphics/fb0/free_scale
echo 0 > /sys/class/graphics/fb1/free_scale
```

**Comment by SumavisionQ5** [comment]
Result of following line is: 1080p60hz
cat /sys/class/display/mode
And I typed the 4 lines and rebooted, still same problem happened.
![tim 20170622125240](https://user-images.githubusercontent.com/29566203/27417804-8f9c5284-5749-11e7-8873-908c0500120d.png)

**Comment by shantigilbert** [comment]
no, don't reboot, it should change instantly.

**Comment by SumavisionQ5** [comment]
No, it does not work, neither.
![20170622130721](https://user-images.githubusercontent.com/29566203/27418132-b84c2f2c-574b-11e7-8c4b-8ae56a21ab76.png)

**Comment by shantigilbert** [comment]
That looks like a very small screen, do you know the resolution? 

and this is connected on CVBS right?

**Comment by SumavisionQ5** [comment]
Yes, this is connected on CVBS, PAL.
I think the screen just shows a small part of 1920*1080.

**Comment by shantigilbert** [comment]
Its weird that your system is not detecting the correct resolution, do you know the resolution of that screen? does anything change when you send those commands on the screen?

Try this:

```
fbset -fb /dev/fb0 -g  640 480 1920 2160 16
fbset -fb /dev/fb1 -g 16 16 16 16 16
echo 0 > /sys/class/graphics/fb0/free_scale
echo 0 > /sys/class/graphics/fb1/free_scale
echo 640  > /sys/class/graphics/fb0/scale_width
echo 480 > /sys/class/graphics/fb0/scale_height
echo 1 > /sys/class/video/disable_video
```

**Comment by SumavisionQ5** [comment]
Still no luck.
![tim 20170622132050](https://user-images.githubusercontent.com/29566203/27418393-72c2162c-574d-11e7-900c-9ad1690058d7.png)
![tim 20170622132124](https://user-images.githubusercontent.com/29566203/27418394-72ec4474-574d-11e7-838a-cf8fe10f0dab.jpg)
The resolution of my screen? I don't know.
I did nothing when I sent those commands on the screen.
I need to go to work, now. But I will continue testing tonight if you need.

**Comment by shantigilbert** [comment]
Well it switched to 16bpp instead of 32 so it is reading the commands.

**Comment by SumavisionQ5** [comment]
Someone tested your build and said it was working correctly under KODI, but for ES, no.
My TV is DIYed from an Android pad（7 inch） and I think it is OK to show CVBS signal.
So maybe it still needs some coding work to output CVBS for ES.

**Comment by shantigilbert** [comment]
put this in the autostart.sh file and reboot.

```
echo 480p60hz > /sys/class/display/mode
fbset -fb /dev/fb0 -g  640 480 640 0 32
```

it switches correctly to 480p on my TV but I use HDMI.

**Comment by SumavisionQ5** [comment]
It doesn't work :(
![tim 20170622193023](https://user-images.githubusercontent.com/29566203/27432003-0e5e982a-5781-11e7-9dd6-3ae43021ef2b.jpg)

**Comment by shantigilbert** [comment]
Did it change at all? or does it look the same? I can't tell because your photos are all different. 

If it did change then it means (I think) that your screen is even lower than 480p so you will have to test which resolution it supports.

I ran out of ideas and your screen seems like a special kind of deal, do you have another screen that uses CVBS? maybe a regular TV?

I don't have neither a box that can output CVBS nor a TV so I cannot really properly test.

**Comment by SumavisionQ5** [comment]
It looked the same as I changed it before.
My screen supports all kinds of signal except 4k resolution.
Not only me, but also someone else who tested it had the same peoblem. So I think it is not TV related. BTY, CVBS can only output 480i and 576i, no progressive signal can be output via CVBS.
I am freezed at sx05re logo when I changed to 480p60hz via HDMI output.
Though I have not gotten time to test KODI, my friend told me it was OK under KODI via CVBS output. I will test CVBS output under KODI this weekend, and sorry for the delay of response.

**Comment by shantigilbert** [comment]
If that is the case then sorry but it is probably out of my skills to fix it.

**Comment by SumavisionQ5** [comment]
That's OK. After all, you had tried your best.

**Comment by shantigilbert** [comment]
I will keep looking, maybe check how kodi does it, but it will be hard to test without cvbs to output

**Comment by kszaq** [comment]
I think command to enable free_scale from 1080p to PAL CVBS is:
```
fbset -fb /dev/fb0 -g 1920 1080 1920 2160 32
fbset -fb /dev/fb1 -g 32 32 32 32 32
echo 0 0 1919 1079 > /sys/class/graphics/fb0/free_scale_axis
echo 0 0 719 575 > /sys/class/graphics/fb0/window_axis
echo 1920 > /sys/class/graphics/fb0/scale_width
echo 1080 > /sys/class/graphics/fb0/scale_height
echo 0x10001 > /sys/class/graphics/fb0/free_scale
````

**Comment by shantigilbert** [comment]
@kszaq I appreciate the help, hopefully this will fix the problem that @SumavisionQ5 is having!

**Comment by SumavisionQ5** [comment]
@shantigilbert @kszaq Thank you very much, now it works!

**Comment by WXDFever** [comment]
@SumavisionQ5 hello, sorry to bother you. So you got all figured out? Just try the command kszaq provided and it worked? Now you got full screen show on your monitor with CVBS? What is the resulotion of this? 480P now?

Thanks

**Comment by SumavisionQ5** [comment]
别活在我的阴影之下，自己去折腾吧……
