### ISSUE TITLE
tmpfiles.d error when using sx05reroms symlink

### ISSUE THREAD

**Issue by jaykass** [shantigilbert/LibreELEC.tv#45]
when using a usb/sdcard for roms and using sx05reroms to point to their location, the logic used in autostart.sh to create a symbolic link causes tmpfiles.d errors on subsequent boot up. see log below. 

additionally, this logic also causes the symlink to be copied to /storage/roms2 each time autostart.sh is run. 

```
● systemd-tmpfiles-setup.service - Create Volatile Files and Directories
   Loaded: loaded (/usr/lib/systemd/system/systemd-tmpfiles-setup.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-04-11 18:49:09 PDT; 2 months 9 days ago
     Docs: man:tmpfiles.d(5)           man:systemd-tmpfiles(8)
  Process: 2124 ExecStart=/usr/bin/systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev (code=exited, status=1/FAILURE)
 Main PID: 2124 (code=exited, status=1/FAILURE)

Apr 11 18:49:09 Sx05RE systemd[1]: Starting Create Volatile Files and Directories...
Apr 11 18:49:09 Sx05RE systemd-tmpfiles[2124]: [/usr/lib/tmpfiles.d/retroarch-userdirs.conf:26] Duplicate line for path "/storage/screenshots", ignoring.
Apr 11 18:49:09 Sx05RE systemd-tmpfiles[2124]: "/storage/roms" already exists and is not a directory.
Apr 11 18:49:09 Sx05RE systemd-tmpfiles[2124]: Failed to create directory or subvolume "/storage/roms/downloads": No such file or directory
Apr 11 18:49:09 Sx05RE systemd[1]: systemd-tmpfiles-setup.service: Main process exited, code=exited, status=1/FAILURE
Apr 11 18:49:09 Sx05RE systemd[1]: Failed to start Create Volatile Files and Directories.
```

Though retroarch appears to be operating properly otherwise.

**Comment by shantigilbert** [comment]
Yes it is a known issue, although it is a bit annoying it is harmless, everything will work fine. The main problem is that its trying to create/mount the /storage/roms folder but it already exists as a symlink. /storage/roms2 is a backup of the original /roms folder in case you have some roms there.

I've been trying to find a way to suppress these errors but it is not on my high priority list as it doesn't make anything fail (that I can tell)

**Comment by jaykass** [comment]
I'm still a bit of a Linux beginner. Would mounting an overlay be a solution?

**Comment by shantigilbert** [comment]
I do have a sort of solution but I need to test it.

**Comment by shantigilbert** [comment]
This is fixed with this commit
https://github.com/shantigilbert/LibreELEC.tv/commit/48ceac9848f21b13f1a3a1a85a5697b61a1fa553
