### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/LibreELEC.tv#47]
Hello, shantigilert. Sorry to bother, thanks for bringing this new 1.6 version to us. We love it! But still, we have some issues, hope you can help:
1. I see there are some themes there, but I want to delete some of them. When the system reboot I see the deleted themes are coming back, can you tell me how to delete them and not them coming back?
2. I see there is a rom called 'dummy' in N64, like question 1, I deleted it but it's coming back, how can I delete it forever?
3. I am from China, to let the gamelist show in Chinese, I managed to put a Chinese font file in all the themes so it worked. But the space between 2 games are too large, it never happened in 1.5 version. Can you help?
4. Continue as question 3, I managed to use Chinese font file, but when I put like 1000 roms and pull the gamelist to select game, the system will be hang.... I have to force to turn off my device... I managed to find a solution is that I use another Chinese font file(which is smaller like 2MB), is there any solution to this?
5. If I can provide you a Chinese font file, can you let the system support Chinese font in next 1.7 version?

So sorry to ask so many questions, thanks you all for making this fantastic system!

**Comment by shantigilbert** [comment]
@WXDFever 

1.  Please download the newest fixed version (Fix 2) it should only include one theme
2.  That ROM cannot be removed currently, and it only gets copied if the ROMS folder does not exist, its a fail-safe so that ES can boot. But I just saw an error on the code that can be improved for next version.
3.  Emulationstation changed a lot from version 1.5 to v1.6, it is not something that I can/want to change, you will need to find a font that works for you, sorry. 
4. You said you found a solution... I guess that is the solution?
5. I can try but I can't make any promises since I can't read chinese I have no idea how its supposed to look, and also it needs to be a public domain font or a FREE font, I won't include anything commercial/ilegal.

**Comment by WXDFever** [comment]
@shantigilbert 
Hello, thanks for your attention and your reply. Here are my newest progress
1. I have downloaded the fix2 version and it's one theme there. It helped a lot, but is there a way that I can delete it? Of course I will put another theme there and switch to it before I delete it. Sorry for pushing...

2. Got your idea,thanks

3. Maybe I didn't express well, sorry for my bad English, I posted 2 images here, could you please take a look? That's what I mean, can't make 1.6's gamelist like 1.5 before

4. Yeah, that is the solution, but now I have question 3 which the space between game names are too large. Let's close this issue since it's same as 3.

5. I will check more information about the font and make sure it's legal and not commercial.

Thanks again for bringing up this project, really love it.
![1 5 game space](https://user-images.githubusercontent.com/29010142/27650808-b453d484-5c68-11e7-835a-893344c3e0ab.png)

**Comment by WXDFever** [comment]
@shantigilbert 
![1 6 game space 1](https://user-images.githubusercontent.com/29010142/27651541-48b284c0-5c6b-11e7-9d15-940087021c39.jpg)

**Comment by shantigilbert** [comment]
@WXDFever 

Emulationstation had a lot of fixes with how the text was displayed that is why you see those changes, you are going to need a new theme, or a font that works for you.

The theme cannot be deleted, but you can add more to /storage/.emulationstation/themes

**Comment by WXDFever** [comment]
@shantigilbert  Thanks for your reply. Guess can't solve these 2 issues, thanks anyway, my friends and I will keep trying for the space thing. 

Many thanks to you, buddy.

**Comment by shantigilbert** [comment]
You are welcome

**Comment by WXDFever** [comment]
@shantigilbert Thanks, buddy. We finally found a font which is nice and the space is good, also the system will not hang. Thanks for your support

**Comment by shantigilbert** [comment]
I am glad you did! What was the name of it ? Just for the record

**Comment by WXDFever** [comment]
the name of the font is: Sans MT TC BIG5HK_S60C.
BTW: are you working on v1.7? lol

**Comment by shantigilbert** [comment]
Yes I am working on v1.7 but not sure when it will be done.

**Comment by WXDFever** [comment]
@shantigilbert  glad to know. love this sx05re idea. Thanks
