### ISSUE TITLE
Regarding 1.6.5

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/LibreELEC.tv#52]
Hello, I see you have released 1.6.5. I was wondering if you could tell me some details:

Emulationstation 2.40 with new Favorites feature.
(Is that the feature that you can put your favorite games together even there are different games on different console?)

Many small bug fixes.
(What are these bugs? Like you can't choose 'setting' in retroarch or it will stuck for a while and restart retroarch?)

Thanks for your support

**Comment by WXDFever** [comment]
Hey, for the 1.6.5. I see you deleted dummy in N64, is that for me since I reported? I am so grateful. But it seems like we get error
![qq 20170710195829](https://user-images.githubusercontent.com/29010142/28017119-355184b0-65aa-11e7-8390-b7a8bd808fa8.jpg)

**Comment by shantigilbert** [comment]
Do you have any roms?

That is not an error it's saying it can find any roms in the paths especified, you need to have Roms?

**Comment by WXDFever** [comment]
I will try to add one rom tonight. Thanks for you reply

**Comment by shantigilbert** [comment]
initial boot time? or once it goes into Emulationstation? I haven't noticed a difference to be honest. if you are running from a SD card make sure its class 10.

**Comment by WXDFever** [comment]
I am a rookie, not sure how to describe. I mean the time we are watching the 'sx05re' logo. For 1.5, I only need to watch for like 30 secs to get in ES. But for 1.6, I usually have to watch that for like 2 mins

**Comment by shantigilbert** [comment]
I have mine installed on the internal memory and I can't see any difference, not sure why it takes that long for you. The initial boot does take a while, but after that it shouldn't.

**Comment by WXDFever** [comment]
hmm, I see. We usually installed it on TF card, the internal memory keeps the Android system. Thanks for your reply, buddy.

**Comment by shantigilbert** [comment]
make sure your TF card is fast enough

**Comment by WXDFever** [comment]
yep, I use the same TF card on both 1.5 and 1.6. it was class 10. So sorry for bringing so much trouble to you, thanks for your help.
