### ISSUE TITLE
External Hard Drive Issue

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/LibreELEC.tv#54]
I am so sorry to bother you again..... I tried to put ps and dc game roms in external USB HDD hard drive, But when I tried to launch games, it's slow and lag, the sound is not good either. Seems like it's not even USB speed. Do you have any solution? 

Thanks

**Comment by shantigilbert** [comment]
Do the games play ok when you run then from and SD? 

Also the n64, psx and DC emus are hit and miss not all games play correctly

**Comment by WXDFever** [comment]
yes, the same games works fine from tf card, but not good with hard drive

**Comment by shantigilbert** [comment]
Then it sounds like it's a problem with your HDD or your device, not sure what I can do to help .

**Comment by shantigilbert** [comment]
Just FYI I run all of my roms from the HDD without a problem.

**Comment by WXDFever** [comment]
alright, I will try another one, thanks for your help :+1:
