### ISSUE TITLE
Emulationstation crashes with Chinese rom name in gamelist.xml

### ISSUE THREAD

**Issue by asakous** [shantigilbert/LibreELEC.tv#55]
I have a  gamelist.xml that around 165 Kbyte (1200+ roms). Every time I scroll to middle of game list , the Emulationstation always crash。dmesg shows 『unhandled level 3 translation fault (11)』
I use same list on RetroPie and it doesn't have the problem.

**Comment by shantigilbert** [comment]
Please refer to issue #47

**Comment by asakous** [comment]
I change font but it doesn't help. ES still crash and reboot. 
my font name is S60TCHK_C.ttf . it should be the "Sans MT TC BIG5HK_S60C" according to #47.
I even tried very small file size of font , around 500 Kbyte , no luck. still crash .

**Comment by shantigilbert** [comment]
Sorry I really don't know how to help as I don't speak Chinese (wish I did tho :P ) I will leave this issue open just in case somebody else knows whats going on.

**Comment by asakous** [comment]
a Chinese forum released a newer version of Emulationstation seems fixed the problem.
