### ISSUE TITLE
Request of Desktop

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/LibreELEC.tv#58]
Hey, Bro!  Thanks for the latest 1.6.5. We have enjoyed it. 

I guess you must be working on the next version? Here is a request, would you please try to add a lxde desktop in the later version of sx05re?

Thanks for your help

**Comment by shantigilbert** [comment]
I am working on 1.7 but at the moment my build computer has died. Trying to get the money to fix it and when I get it fixed I will continue. I will look into the desktop but I am not sure why you need that .

**Comment by WXDFever** [comment]
oh, sorry to hear that. The reason for that is one of my friends needs that. Guess he's trying to use that as a linux computer? I am not really good at that, but it seems interesting since I have used the desktop in retroorangepi and it helps to expand the tf card's space. If you can add that, it will be great and it is in ES, just like the DC in 1.6, right? Thanks for looking into it, and hope you can fix your computer soon

**Comment by shantigilbert** [comment]
I don't think a desktop will be added. This is based on libreelec which has all of that stripped to make it lighter and faster. There are other options for the S905 if he wants to use it as a   Linux computer.
