### ISSUE TITLE
Option in cfg to not start Emulation Station on Retroarch Quit

### ISSUE THREAD

**Issue by zach-morris** [shantigilbert/LibreELEC.tv#59]
Would it be possible to add some config setting to prevent starting emulation station after Retroarch quits?  I see the code to start ES on quit is [here](https://github.com/shantigilbert/LibreELEC.tv/blob/Sx05RE/packages/sx05re/retroarch-sx05re/patches/retroarch-sx05re-10-Exit_menu.patch#L26).  Alternatively, if the option can be changed to start Kodi instead of ES that would be cool too.  I'd like to use this build to launch games from Kodi if possible.

Thanks!

**Comment by shantigilbert** [comment]
Try the no-es branch

**Comment by zach-morris** [comment]
That would work, but then ES isn't an option if the user wants it.  Is it possible to have the best of both worlds?  I was thinking something like:
```
@@ -1797,6 +1797,22 @@
          }
          break;
       case CMD_EVENT_QUIT:
+      #Exit Back to Kodi
+      if(settings->bools.exit_to_kodi)
+      {
+      remove("/var/lock/start.retro");
+      system("touch /var/lock/start.kodi");
+      system("systemctl start kodi.service");
+      system("systemctl stop retroarch.service");
+      }
+       else
+      {
+      #Exit back to ES
+      remove("/var/lock/start.retro");
+      system("touch /var/lock/start.games");
+      system("systemctl start emustation.service");
+      system("systemctl stop retroarch.service");
+      }
          return retroarch_main_quit();
       case CMD_EVENT_CHEEVOS_HARDCORE_MODE_TOGGLE:
 #ifdef HAVE_CHEEVOS
```

Along with the correct init of bools.exit_to_kodi, and then the user can just set it up in the config, otherwise it would default to exit to ES as you have currently.

**Comment by shantigilbert** [comment]
I will try this and see if it works, if it does I will push it.

**Comment by shantigilbert** [comment]
Well I tried if but I get this error:

`command.c:1814:18: error: 'settings_t {aka struct settings}' has no member named 'sx05re_exit_to_kodi'
       if(settings->sx05re_exit_to_kodi)
`

even tho I added it to configuration.h

`--- ./configuration.h	2017-08-14 02:20:37.546187576 -0500
+++ ./configuration.h	2017-08-14 02:20:46.390236188 -0500
@@ -47,6 +47,8 @@
    {
       bool placeholder;
 
+      /* sx05re */
+      bool sx05re_exit_to_kodi;
       /* Video */
       bool video_fullscreen;
       bool video_windowed_fullscreen;`

this is the

**Comment by zach-morris** [comment]
Cool, i'll give it a try.  Thanks for the quick patch!

**Comment by shantigilbert** [comment]
Did this work?

**Comment by zach-morris** [comment]
I can't get this to build for some reason, but I think thats likely my setup and lack of knowledge (trying to do this on Ubuntu).  I'll keep fighting with it and let you know if I can get it working and what the result is

**Comment by zach-morris** [comment]
Built and updated via the update folder.   The setting doesn't seem to do anything unfortunately as either "true" or "false"

**Comment by shantigilbert** [comment]
I will test this tomorrow and see if I can see why this is happening.

**Comment by zach-morris** [comment]
I'm not a C guy, but I'm guessing it also has to be defined [here](https://github.com/libretro/RetroArch/blob/master/configuration.c#L1109) so a default value is defined.

**Comment by shantigilbert** [comment]
I modified the patch, but I haven't tested it yet, can you let me know if this one works?

**Comment by zach-morris** [comment]
Beautiful, that worked!  Tested both no settting, "true" and "false" and they all worked as expected.  I'm launching retroarch from Kodi by having my addon run a shell script and it exits to Kodi with that setting enabled.

Thanks again!

**Comment by shantigilbert** [comment]
Cool, I will close this issue :)
