### ISSUE TITLE
Regarding to 1.7

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/LibreELEC.tv#66]
Thanks for the 1.7. We have tried it during the weekend. Here are some details:

1. So the ES version is 2.4, is there any chance you can update it to 2.6? 
2. I used a software called FLASHFXP(which helps me to put roms in via FTP), however, I failed to connect my device under 1.7(it works fine during 1.6.5 and other version)
3. A suggestion: maybe you can get more permission for SMB? Like theme folder, rom folder, it will be more convenient.

Thanks for your hard work

**Comment by shantigilbert** [comment]
I can check this, but as I mentioned earlier it's hard at the moment as I have no working decent laptop, so I appreciate the reports I can try to fix this issues and you can test them later.

What do you mean by FlashFXP not connecting? Are you using the IP?

**Comment by WXDFever** [comment]
Hmm, in earlier version, like 1.6.5 or 1.6. I can always connect my device by FTP(username: root, password: sx05re), it helps me to put bios and roms or themes, but now in 1.7 version, it's not working. Also I tried with putty, can't connect as well.

Sorry about your laptop, it's ok, anytime you release new version, we will be happy to test!

**Comment by WXDFever** [comment]
Hey, buddy, Maybe we can help you with the laptop, is there any way you can leave us a way of donation? Some of my friends may help :)

**Comment by shantigilbert** [comment]
I do have a paypal account, donations are not needed, but are truly appreciated :) shantic@gmail.com 
Thanks
