### ISSUE TITLE
Compile fails on 8.2 branch

### ISSUE THREAD

**Issue by zach-morris** [shantigilbert/LibreELEC.tv#76]
Tried a fresh clone of Sx05RE_8.2:
```
git clone -b Sx05RE_8.2 https://github.com/shantigilbert/LibreELEC.tv.git SX05RE
cd SX05RE
sudo make image project=S905 ARCH=arm DISTRO=Sx05RE

ERROR:  Architecture not found, use a valid Architecture

Valid Architectures for your project:
- x86_64

```

Previously this worked like a charm.

**Comment by shantigilbert** [comment]
hmm, let me check this, I just compiled this yesterday and it work, but I haven't done it from scratch in a while. will check tonight.

**Comment by zach-morris** [comment]
Error on my part.  I put in SXO5RE instead of SX05RE.  It still attempted so I missed the typo.  Sorry for wasting your time :-/

**Comment by shantigilbert** [comment]
I am glad it's working!
