### ISSUE TITLE
Request regarding to ES 2.7.1

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/LibreELEC.tv#78]
Hello, buddy. Did you buy a new laptop? I am not sure if it's appropriate to request some help here since not sure if you got the new laptop to 'work'.

Here is the issue: ES 2.7.1 (0974f1c), can't apply to the sx05re now, do you have time to update the patch to make it work.

p.s. I am a noob, not sure if you can understand what I mean.
Again, thanks for your effort.

**Comment by shantigilbert** [comment]
I didn't get a laptop yet. But I am already working on patch for ES :)

**Comment by shantigilbert** [comment]
This is fixed on commit 09fd741
