### ISSUE TITLE
Regarding to #78

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/LibreELEC.tv#82]
Hello, buddy. How are you doing recently?

So I have encountered another problem. With the new patch of issue #78 mentioned, I can't get into any game in the new ES, when I tried to launch a game from the gamelist, ES reboot itself.  When I was in retroarch xmb interface, the option 'Quit Retroarch' also makes ES reboot instead of backing to the gamelist. I am not sure if I did anything wrong. Could you please have a check on the patch when you are available?

Thanks in advance!

**Comment by shantigilbert** [comment]
Did you upgrade or install from scratch ? I've had no problems with this, so its very weird.

**Comment by WXDFever** [comment]
Well, I did install from scratch, based on your code LE 8.2, and here is the video:
https://www.youtube.com/watch?v=muSE4P2avd4&feature=youtu.be

As you can see, when I choose 'quit retroarch', it should quit to the gamelist, but now it seems like the ES reboots since it's back to the emulator choose menu. Looks like ES collapses.

Also there is another tiny issue:
![quit](https://user-images.githubusercontent.com/29010142/33973192-8806dc2c-e0bc-11e7-9392-545228786acb.jpg)

the quit should be 'retroarch', right?

**Comment by WXDFever** [comment]
update:

Well, I have tried ES V2.7.1, and there is no problem at all.  It seems like the issue only happens on V2.7.3. Since V2.7.4 is the latest, please ignore the issue for 2.7.3 and could you please make the patch for V2.7.4? Also RA updates to 1.6.9 now, could you please also update it?

Sorry for brought up so much trouble.

**Comment by shantigilbert** [comment]
Is no trouble.

I have updated ES and RA.

**Comment by WXDFever** [comment]
@shantigilbert 
Thanks, buddy, I will take a look at the new version of ES and RA later, will update here once I found any problems, thanks

**Comment by shantigilbert** [comment]
I think I finally ran into the problem you mentioned, it does not go back smoothly to ES after closing RA. But I have to figure out why this is happening.

**Comment by WXDFever** [comment]
yep，ES 2.7.3 and 2.7.4 both have the problem, 2.7.1 works fine

**Comment by WXDFever** [comment]
it seems like ES collapses cos when you quit RA, it should return to the gamelist in ES, but now ES reboot

**Comment by shantigilbert** [comment]
I think I found the problem and I am currently testing to see if my solution works, will update tonight if everything works out fine.

**Comment by shantigilbert** [comment]
Unfortunately it didn't fix the problem, it is still present, it seems the first time you back up RA it works, but the second time and on it always crashes with a segmentation fault. I am going to recompile without any patches applied and see if it does the same.

**Comment by shantigilbert** [comment]
well it seems compiling without any patch results in the same behavior, the dmesg I get when I quit is as follows:

```
`[  668.860603@2] emulationstatio[3414]: unhandled level 1 translation fault (11) at 0xbe439d05, esr 0x92000005
[  668.860614@2] pgd = ffffffc010ff6000
[  668.860620@2] [be439d05] *pgd=0000000000000000
[  668.860626@2] 
[  668.860635@2] CPU: 2 PID: 3414 Comm: emulationstatio Tainted: G           O 3.14.29 #1
[  668.860642@2] task: ffffffc00eea7500 ti: ffffffc065a20000 task.ti: ffffffc065a20000
[  668.860658@2] PC is at 0xf70f858c
[  668.860664@2] LR is at 0xf70f920c
[  668.860670@2] pc : [<00000000f70f858c>] lr : [<00000000f70f920c>] pstate: a0000010
[  668.860675@2] sp : 00000000ff99b888
[  668.860679@2] x12: 00000000be439d01 
[  668.860685@2] x11: 00000000ff99b9ac x10: 00000000ff99b9d4 
[  668.860692@2] x9 : 00000000ff99b958 x8 : 00000000000d28d2 
[  668.860698@2] x7 : 00000000ff99b950 x6 : 0000000000000000 
[  668.860705@2] x5 : 0000000000a60a78 x4 : 00000000449c2f5b 
[  668.860711@2] x3 : 00000000f711dfb4 x2 : 00000000ff99b950 
[  668.860718@2] x1 : 00000000449c2f5b x0 : 00000000000d28d2 
[  668.860724@2] 
[  673.528533@3] aml_snd_card: audio speaker off`

so any help with this bug is greatly appreciated. 
```

**Comment by shantigilbert** [comment]
This should be fixed now, it seems the S905 conflicted with the newly added CEC support.
