### ISSUE TITLE
tvheadend4.2 con't run with rev 1.7

### ISSUE THREAD

**Issue by xiaole51** [shantigilbert/LibreELEC.tv#87]
I can update from 1.6.5 to 1.7
but tvheadend4.2 can't run ,libssl.so.39  not find.

`/storage/.kodi/addons/service.tvheadend42/bin/tvheadend: error while loading shared libraries: libssl.so.39: cannot open shared object file: No such file or directory`

install tvheadend in Docker can work

**Comment by shantigilbert** [comment]
a while ago, the system was migrated to openssl and libssl was removed. I am not sure if this is something to do with the upgrade or if its something with the package, I will check

**Comment by shantigilbert** [comment]
Did you upgraded or installed from scratch?

**Comment by xiaole51** [comment]
I'm unzip 1.7 img file, copy SYSTEM and Kernel files to 1.6.5 USB storage. 
after install tvheadend 4.2 change to 4.3 executable file can work.

**Comment by shantigilbert** [comment]
Is this still a problem with 1.8.2?

**Comment by shantigilbert** [comment]
No reply so I will close this, feel free to open it again if you still have the problem
