### ISSUE TITLE
VLC file is missing

### ISSUE THREAD

**Issue by windy2006** [shantigilbert/LibreELEC.tv#88]
An error occurs when getting the pack of VLC, all mirros return the 404 error.

The diretory of VLC at "http://sources.libreelec.tv/mirror/" has been removed.

But I can find some new version at "https://nightlies.videolan.org/build/source/", may I use the lasted one instead?

**Comment by shantigilbert** [comment]
According to the package.mk of VLC its pulling the source from 

```

PKG_NAME="vlc"  

PKG_VERSION="3.0.0"  

PKG_REV="20170220-0237-git"  

PKG_URL="https://nightlies.videolan.org/build/source/$PKG_NAME-$PKG_VERSION-$PKG_REV.tar.xz"
```
So the final URL is

https://nightlies.videolan.org/build/source/vlc-3.0.0-20170220-0237-git.tar.xz

that file seems to have been deleted, you can try and use another one but I would recomend staying in the 3.0.0 version

vlc-3.0.0-20171228-0223-rc5.tar.xz 

change the PKG_REV to 20171228-0223-rc5 and see if that works for you :)

**Comment by windy2006** [comment]
Yes, I have find the package.mk, but I have changed the PKG_REV to "20171023-0237-git". Because I think the sufix of "0237" is neccessary, and rc or dev version isn't stable, am I right?

**Comment by shantigilbert** [comment]
This was fixed on commit https://github.com/shantigilbert/LibreELEC.tv/commit/63fb56beac161ec7434a6c30fc2323313ffd7fe3
