### ISSUE TITLE
How can I check the bootlog?

### ISSUE THREAD

**Issue by windy2006** [shantigilbert/LibreELEC.tv#90]
I am trying to compile the latest awesome ware by myself, but it always frozen before the logo screen. I also try the one download for the release page, the problem is the same. But the 1.6.5 release runs correct on my device. 

I want to check key point of the problem from the bootlog, how can I find that?

Another question is how can I update es or advmame at the compiled image? It seems  that the compiled system is read only?

**Comment by shantigilbert** [comment]
Unfortunately there is no way to check the bootlog without ssh that I know of. Updating the binaries is not really possible as the system is read only. You could try connecting through ssh and mounting the system as RW, but not sure if that would work.

What device do you have? Did you update the the dtb to the correct one for your device?

**Comment by windy2006** [comment]
Thank you for your reply, I have tried to mount the img file or TF card (with the image) with the re-writable option, but it still read-only, So I thank compiling a newest version is a better way to update all of the stuff.

My device type is S905D and  id is p213, I have replace the dtd file (get from https://sx05.eu/s905/8.2/device_trees/S905D/) which works correct at 1.6.5 to the 512MB partition, and got the frozen screen. I think the system crash at the first step, so the network function doesn't start. Could you give me some idea to trace the error?

Thank you!

**Comment by shantigilbert** [comment]
Does the newest version of Kszaq's LE work on your device?

**Comment by shantigilbert** [comment]
I will close this issue since no reply was given.
