### ISSUE TITLE
Documentation on usage?

### ISSUE THREAD

**Issue by ilikenwf** [shantigilbert/LibreELEC.tv#91]
How does one switch between LE and ES without rebooting...

How does one setup ES so that it doesn't give an error on boot?

There's literally no documentation anywhere that I can find, so I can compile this thing but can't really figure out the usage.

**Comment by ilikenwf** [comment]
I found the launcher addon, thankfully...now to get my samba mount working with ES.

**Comment by ilikenwf** [comment]
Emulation Station, I have no audio...my device only has HDMI audio output so I'm not sure why...adjusting it in ES doesn't fix it...any ideas there too?

**Comment by shantigilbert** [comment]
The no audio part is a known issue, I still have no solution.

**Comment by ilikenwf** [comment]
Since the Joker addon works with audio (no ES, but libretro at least works)
perhaps we can look and see how his builds configure themselves and borrow
whatever tweaks are going on there?

**Comment by shantigilbert** [comment]
Oh libreto has audio on the s905, I meant the ES has no audio, try to change the configuration on retroarch directly to find your audio device, It might not be the same

**Comment by ilikenwf** [comment]
Does it take that in the format of an alsa device? hw:0,1 or whatever?

**Comment by shantigilbert** [comment]
Yes it does.

**Comment by shantigilbert** [comment]
Can you elaborate on this: 

"How does one setup ES so that it doesn't give an error on boot?" 

what error?

There is no documentation because, well I am just one person making this smash up of other projects, and it was mostly intended as a personal project, sorry about that.

**Comment by ilikenwf** [comment]
Sorry, no big deal, just was asking in case these weren't known...

I just hadn't mounted my rom share yet.
