### ISSUE TITLE
Can't boot S905

### ISSUE THREAD

**Issue by xixijojo** [shantigilbert/LibreELEC.tv#96]
cp: write error: No space left on device
***Error in prepare_sysroot: mount common: Could  not mount /dev/SYSTEM ***
### Starting debugging shell... type exit to quit ###
sh: can't access tty: job control turned off

**Comment by shantigilbert** [comment]
What version are you using? compiled it yourself?

**Comment by xixijojo** [comment]
I found this “https://forum.libreelec.tv/thread/11282-can-t-boot-custom-libreelec-8-2-sx05re-build-for-amlogic/“. 
I edited this file projects/S805/linux/linux.arm.conf 
“CONFIG_CMDLINE="console=tty0 consoleblank=0 systemd.show_status=auto noram” 
Now it works.
