### ISSUE TITLE
S905_1GB can't compile and pass? 

### ISSUE THREAD

**Issue by xixijojo** [shantigilbert/LibreELEC.tv#97]
if PROJECT=S905_1GB then can't compile and pass.
stop on package media_buile
if PROJECT=S905 can compile and pass

**Comment by shantigilbert** [comment]
unfortunately it was not tested properly and its not working. revert this commit 

https://github.com/shantigilbert/LibreELEC.tv/commit/f2e3371fa4138924dcd32eff29a4dfe368323744#diff-708fce2b98cae7109f84bb7011142f00

and compile for the regular S905

**Comment by xixijojo** [comment]
sorry,i mean 
make image PROJECT=S905 ARCH=arm DISTRO=Sx05RE can compile and pass.
make image PROJECT=S905_1GB ARCH=arm DISTRO=Sx05RE stop on compile package "media_buile".

**Comment by shantigilbert** [comment]
I know what you mean and to compile for 1gb you need to revert that commit I gave you.

**Comment by xixijojo** [comment]
PROJECT=S905_1GB compile error:
mekeeping.h: No such file or directory
 #include <linux/timekeeping.h>
                               ^
compilation terminated.
make[4]: *** [scripts/Makefile.build:308：/home/johnin/Sx05RE/build.Sx05RE-S906.arm-1.8.2/media_build-2017-04-17-rpi/v4l/cxd2880_stopwatch_port.o] error 1

**Comment by shantigilbert** [comment]
Please read my reply, it has already been answered.
